spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urbannest
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: urbannest.test@gmail.com
    password: pamq aljo iovd udxp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
